services:
  front:
    image: zabbix/zabbix-web-nginx-pgsql:7.0.17-ol
    hostname: <HOSTNAME>
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: "1G"
      placement:
        constraints: [node.role == manager]
    networks:
      - <NETWORK>
    ports:
      - '8080:8080'
    environment:
      DB_SERVER_HOST: zabbixdbserverhost
      DB_SERVER_PORT: 5432
      POSTGRES_USER: <DB_USER>
      POSTGRES_PASSWORD: <DB_PASSWORD>
      POSTGRES_DB: zabbix
      ZBX_SERVER_NAME: <ZABBIXNAME>
    logging:
      driver: "json-file"
      options:
        max-size: "100m"

networks:
  <NETWORK>:
    external: true
