services:
  server-ha1:
    user: "0"
    hostname: zabbixha1
    image: zabbix/zabbix-server-pgsql:7.0.17-ol
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: "1G"
      placement:
        constraints: [node.role == manager]
    ports:
      - '10051:10051'
    networks:
      - <NETWORK>
    environment:
      TZ: "America/Sao_Paulo"
      DB_SERVER_HOST: zabbixdbserverhost
      DB_SERVER_PORT: 5432
      POSTGRES_USER: <DB_USER>
      POSTGRES_PASSWORD: <DB_PASSWORD>
      POSTGRES_DB: zabbix
      ZBX_CACHESIZE: 64M
      ZBX_HISTORYCACHESIZE: 64M
      ZBX_STARTPOLLERS: 5
      ZBX_STARTCONNECTORS: 1
      ZBX_STARTPREPROCESSORS: 5
      ZBX_STARTPOLLERSUNREACHABLE: 5
      ZBX_STARTHISTORYPOLLERS: 5
      ZBX_STARTTRAPPERS: 5
      ZBX_STARTHTTPPOLLERS: 5
      ZBX_STARTDBSYNCERS: 1
      ZBX_HISTORYCACHESIZE: 64M
      ZBX_HISTORYINDEXCACHESIZE: 64M
      ZBX_HISTORYSTORAGEDATEINDEX: 0
      ZBX_TRENDCACHESIZE: 64M
      ZBX_VALUECACHESIZE: 64M
      ZBX_STARTLLDPROCESSORS: 1
      ZBX_STARTPINGERS: 1
      ZBX_TIMEOUT: 20
      ZBX_STARTPROXYPOLLERS: 1
      ZBX_STARTLLDPROCESSORS: 1
      ZBX_LISTENPORT: 10051
      ZBX_DEBUGLEVEL: 3
      ZBX_HOUSEKEEPINGFREQUENCY: 0
      ZBX_MAXHOUSEKEEPERDELETE: 2000
      ZBX_DB_NAME: zabbix
      ZBX_ENABLE_SNMP_TRAPS: "true"
      ZBX_STARTALERTERS: 1
      ZBX_NODEADDRESS: zabbixha1
      ZBX_HANODENAME: zabbixha1    
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
  server-ha2:
    user: "0"
    hostname: zabbixha2
    image: zabbix/zabbix-server-pgsql:7.0.17-ol
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: "1G"
      placement:
        constraints: [node.role == manager]
    ports:
      - '10051:10051'
    networks:
      - <NETWORK>
    environment:
      TZ: "America/Sao_Paulo"
      DB_SERVER_HOST: zabbixdbserverhost
      DB_SERVER_PORT: 5432
      POSTGRES_USER: <DB_USER>
      POSTGRES_PASSWORD: <DB_PASSWORD>
      POSTGRES_DB: zabbix
      ZBX_CACHESIZE: 64M
      ZBX_HISTORYCACHESIZE: 64M
      ZBX_STARTPOLLERS: 5
      ZBX_STARTCONNECTORS: 1
      ZBX_STARTPREPROCESSORS: 5
      ZBX_STARTPOLLERSUNREACHABLE: 5
      ZBX_STARTHISTORYPOLLERS: 5
      ZBX_STARTTRAPPERS: 5
      ZBX_STARTHTTPPOLLERS: 5
      ZBX_STARTDBSYNCERS: 1
      ZBX_HISTORYCACHESIZE: 64M
      ZBX_HISTORYINDEXCACHESIZE: 64M
      ZBX_HISTORYSTORAGEDATEINDEX: 0
      ZBX_TRENDCACHESIZE: 64M
      ZBX_VALUECACHESIZE: 64M
      ZBX_STARTLLDPROCESSORS: 1
      ZBX_STARTPINGERS: 1
      ZBX_TIMEOUT: 20
      ZBX_STARTPROXYPOLLERS: 1
      ZBX_STARTLLDPROCESSORS: 1
      ZBX_LISTENPORT: 10051
      ZBX_DEBUGLEVEL: 3
      ZBX_HOUSEKEEPINGFREQUENCY: 0
      ZBX_MAXHOUSEKEEPERDELETE: 2000
      ZBX_DB_NAME: zabbix
      ZBX_ENABLE_SNMP_TRAPS: "true"
      ZBX_STARTALERTERS: 1
      ZBX_NODEADDRESS: zabbixha2
      ZBX_HANODENAME: zabbixha2
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
networks:
  <NETWORK>:
    external: true
